POST http://localhost:8080/api/products
Content-Type: application/json

{
  "title": "Новый продукт",
  "description": "Описание нового продукта для проверки",
  "contraindications": "Нет",
  "application": "Нанести на кожу",
  "volume": 50,
  "manufacturer_id": 1
}
